const data = {
  products: [
    {
      name: 'Hair Spray',
      slug: 'high quality',
      category: 'Spray',
      image: '/images/hair.jpg', // 679px × 829px
      price: 200,
      countInStock: 10,
      brand: 'TRESemme',
      rating: 9.5,
      numReviews: 10,
      description: '99.9% protection from damages',
    },
    {
      name: 'Colour Spray',
      slug: 'black',
      category: 'Spray',
      image: '/images/black.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Color Splash',
      rating: 9.0,
      numReviews: 10,
      description: 'water resistant',
    },
    {
      name: 'Colour Spray',
      slug: 'White',
      category: 'Spray',
      image: '/images/white.jpg',
      price: 250,
      countInStock: 15,
      brand: 'Muban',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Dashboard spray',
      slug: 'make your dashboard sparkle',
      category: 'sprays',
      image: '/images/dashboard.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Sonax',
      rating: 10,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
